# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - FastAPI-web-app

on: 
  push:
    branches: 
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Checkout GitHub Actions
      uses: actions/checkout@main
      
      
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
        
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: fastapicontainerregistry.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
     
     
    - name: Build and push container image to registry 
      run: |
        docker build . -t fastapicontainerregistry.azurecr.io/fastapi-cd:${{ github.sha }}
        docker push fastapicontainerregistry.azurecr.io/fastapi-cd:${{ github.sha }}
        
        
    - name: Deploy to App Service
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'fastapi-cd'
        images: 'fastapicontainerregistry.azurecr.io/fastapi-cd:${{ github.sha }}'
        slot-name: 'staging'
        
        
    - name: Azure logout
      run: |
        az logout